services:
  - type: web
    name: emotion-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn emotion_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: emotion_project.settings
